### PR TITLE
Add https support

### PR DESCRIPTION
**Pull request by antonstamov**
Add https support requested in https://github.com/crobox/clickhouse-scala-client/issues/170

### CODE REVIEW

**Comment by lwolters** [comment]
Hi @antonstamov Thanks for this pull request. I've quickly checked it and it looks good. Overall a good addition IMHO.
Let's await @sjoerdmulder review but from my side clear to go!

**Comment by sjoerdmulder** [comment]
Yes, the only thing, I don't think we need to add the `certs` as code in the repository right? e.g. they should be in `.gitignore` this so we don't have private key (although just test) stored. Just need to make sure the generate-keys.sh is called before the test.

**Comment by antonstamov** [comment]
@sjoerdmulder Yes, you're right. Fixed.

**Comment by maxcom** [comment]
@sjoerdmulder please review!

**Review by sjoerdmulder — APPROVED** [review]

**Comment by sjoerdmulder** [comment]
@antonstamov sorry for the delay

**Comment by maxcom** [comment]
@sjoerdmulder please release new version with this feature

**Comment by sjoerdmulder** [comment]
Sorry for the delay, I tried but the release fails on the new ssl tests,
and then I gave up. Need to find some time for it

Op ma 25 nov 2024 13:59 schreef Maxim Valyanskiy ***@***.***>:

**Pull request merged**
